server:
 port: 8082
 error:
    include-binding-errors: always
    include-message: always
    include-stacktrace: never
 #spring.datasource.url=jdbc:mysql://localhost:3306/spring_boot
 #spring.datasource.username=root
 #spring.datasource.password=Muzaffer.1990
 #spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
 #servlet:
  #context-path: /api/v0
spring:
 datasource:
   url: jdbc:postgresql://localhost:5432/courses_db
   username: dev_user
   password: Slymn1.
   driver-class-name: org.postgresql.Driver
 jpa:
  hibernate:
   ddl-auto: update
  show-sql: true
  database-platform: org.hibernate.dialect.PostgreSQL9Dialect
  properties:
   '[hibernate.format_sql]': true
logging:
 file:
  name: logs/prcapp.log
 pattern:
  file: "%d %-5level [%thread] %logger:%msg%n"
 level:
  '[org.springframework.web]': WARN
  '[org.hibernate]': INFO
  '[com.tpe]': DEBUG
